var virtualWindows = ({
    application:
    {
        windowStyle: "solid",
        desktop: {
        },
        owner: {
        },
        appearance: {
        }
    },
    controls: [
    ],
    icons: [
     {
            "id": 	"paradigm-window-0",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-1",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-2",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-3",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-4",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-5",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-6",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-7",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-8",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-9",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-10",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-11",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-12",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-13",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-14",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-15",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-16",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-17",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-18",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-19",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-20",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-21",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-22",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-23",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-24",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-25",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-26",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-27",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-28",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-29",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-30",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-31",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-32",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-33",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-34",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-35",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-36",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-37",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-38",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-39",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-40",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-41",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-42",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-43",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-44",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-45",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-46",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-47",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-48",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-49",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-50",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-51",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-52",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-53",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-54",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-55",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-56",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-57",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-58",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-59",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-60",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-61",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-62",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-63",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-64",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-65",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-66",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-67",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-68",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-69",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-70",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-71",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-72",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-73",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-74",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-75",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-76",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-77",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-78",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-79",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-80",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-81",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-82",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-83",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-84",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-85",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-86",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-87",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-88",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-89",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-90",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-91",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-92",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-93",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-94",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-95",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-96",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-97",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-98",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
        , {
            "id": 	"paradigm-window-99",
            "image":	"",
            "text":	"Website | Paradigm",
            "namespace":"paradigm",
            "security": "public",
            "top":      false,
            "left":     false,
            "width":    false,
            "height":   false,
            "minimize":	false,
            "maximize":	false,
            "close":    false,
            "open":     Desktop.toFront,
            "resize":   false,
            "handler":  false
        }
    ]});