<style type='text/css'>
    .form-field-description {
        font-family: arial; font-size: .7em; letter-spacing: 2px
    }
</style>
{assign var=data value=$element->load()}
<table style='width: 100%; height: 100%;'>
    <tr>
        <td valign='middle'>
            <form name="trigger-detector-form" id="trigger-detector-{$data.id}" onsubmit="return false">
                <input type="hidden" name="windowId" id="window-id-{$data.id}" value="{$windowId}" />
                <input type="hidden" id="humble-paradigm-sensor-form-id-{$data.id}" name="id" value="{$data.id}" />
                <input type="hidden" id="humble-paradigm-sensor-form-workflow-id-{$data.id}" name="workflow_id" value="" />
                <input type="hidden" id="humble-paradigm-sensor-form-namespace-{$data.id}" name="namespace" value="paradigm" />
                <input type="hidden" id="humble-paradigm-sensor-form-component-{$data.id}" name="component" value="sensor" />
                <input type="hidden" id="humble-paradigm-sensor-form-method-{$data.id}" name="method" value="trigger" />
                <div style='margin-left: auto; margin-right: auto; width: 545px; font-size: 2em; font-family: sans-serif; color: #333; border-bottom: 1px solid #777; margin-bottom: 6px'>
                    Initial Component Configuration
                </div>
                <div style='margin-left: auto; margin-right: auto; width: 545px; margin-bottom: 25px'>
                    Sensor configuration.  A sensor is listening for a signal, which is comprised of data in the event, and is generated by a detector. Below, please indicate which signal  we are looking for to trigger this workflow:
                </div>
                <div style='margin-left: auto; margin-right: auto; width: 545px'>
                    <img src='/images/paradigm/clipart/sensor2.png' style='float: right; height: 100px' />
                    <input type="radio" name="sensor" id="sensor_glucose_{$data.id}"        value="glucose"         {if (isset($data.sensor) && ($data.sensor=="glucose"))}checked{/if} /> Glucose <br /><br />
                    <input type="radio" name="sensor" id="sensor_bloodpressure_{$data.id}"  value="blood pressure" {if (isset($data.sensor) && ($data.sensor=="blood pressure"))}checked{/if} /> Blood Pressure <br /><br />
                    <input type="radio" name="sensor" id="sensor_heartrate_{$data.id}"      value="heart rate" {if (isset($data.sensor) && ($data.sensor=="heart rate"))}checked{/if} /> Heart Rate <br /><br />
                    <input type="radio" name="sensor" id="sensor_temperature_{$data.id}"    value="temperature" {if (isset($data.sensor) && ($data.sensor=="temperature"))}checked{/if} /> Temperature <br /><br />
                    If one of the above, please specify the event field containing the CellTrak XML<br /><br />
                    Field: <input type="text" name="field" id="sensor_event_field_{$data.id}"      value="{if (isset($data.field))}{$data.field}{/if}" style="padding: 2px; width: 120px; background-color: lightcyan; border: 1px solid #aaf" /><br /><br />

                    <input type="radio" name="sensor" id="sensor_other_{$data.id}"          value="other" {if (isset($data.sensor) && ($data.sensor=="other"))}checked{/if} /> Other:
                    <input type="text"  name="other_value" id="other_value_{$data.id}"      value="{if (isset($data.other_value))}{$data.other_value}{/if}" style="padding: 2px; width: 120px; background-color: lightcyan; border: 1px solid #aaf" /><br /><br /><br />
                    <input type="submit" value=" Set Listener " />
                </div>
                <div style="border-bottom: 1px solid black; margin-left: auto; margin-right: auto; width: 545px; ">
                    <br />
                </div>
            </form>
        </td>
    </tr>
</table>
<script type='text/javascript'>
    Form.intercept($('#trigger-detector-{$data.id}').get(),'{$data.id}','/workflow/sensor/save',"{$windowId}");
    $('#humble-paradigm-sensor-form-workflow-id-{$data.id}').val(Paradigm.actions.get.mongoWorkflowId());
    $('#humble-paradigm-sensor-form-namespace-{$data.id}').val(Paradigm.actions.get.namespace());
</script>