CREATE TABLE paradigm_designer_forms
(
	id INT NOT NULL AUTO_INCREMENT,
	`name` CHAR(32) DEFAULT NULL,
	image CHAR(128) DEFAULT NULL,
	structure TEXT DEFAULT NULL,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
