/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.lang.ast={editor:"Editor de testu arriquecíu",editorPanel:"Panel del editor de testu arriquecíu",common:{editorHelp:"Calca ALT 0 p'ayuda",browseServer:"Restolar nel sirvidor",url:"URL",protocol:"Protocolu",upload:"Xubir",uploadSubmit:"Unvialo al sirvidor",image:"Imaxe",flash:"Flash",form:"Formulariu",checkbox:"Cuadru de marca",radio:"Radio Button",textField:"Campu de testu",textarea:"Área de testu",hiddenField:"Campu tapecíu",button:"Botón",select:"Campu de seleición",imageButton:"Botón d'imaxe",
notSet:"\x3csin afitar\x3e",id:"Id",name:"Nome",langDir:"Direición de la llingua",langDirLtr:"D'izquierda a drecha (LTR)",langDirRtl:"De drecha a izquierda (RTL)",langCode:"Códigu de llingua",longDescr:"URL de descripción llarga",cssClass:"Clases de les fueyes d'estilu",advisoryTitle:"Títulu d'alvertencia",cssStyle:"Estilu",ok:"Aceutar",cancel:"Encaboxar",close:"Zarrar",preview:"Entever",resize:"Redimensionar",generalTab:"Xeneral",advancedTab:"Avanzao",validateNumberFailed:"Esti valor nun ye un númberu.",
confirmNewPage:"Tolos cambios a esti conteníu que nun tean guardaos perderánse. ¿Seguro que quies cargar una páxina nueva?",confirmCancel:"Cambiasti delles opciones. ¿Seguro que quies zarrar la ventana de diálogu?",options:"Opciones",target:"Destín",targetNew:"Ventana nueva (_blank)",targetTop:"Ventana de más arriba (_top)",targetSelf:"La mesma ventana (_self) ",targetParent:"Ventana padre (_parent)",langDirLTR:"Izquierda a drecha (LTR)",langDirRTL:"Drecha a izquierda (RTL)",styles:"Estilu",cssClasses:"Clases de les fueyes d'estilu",
width:"Anchor",height:"Altor",align:"Alliniación",alignLeft:"Izquierda",alignRight:"Drecha",alignCenter:"Centru",alignJustify:"Xustificao",alignTop:"Arriba",alignMiddle:"Al mediu",alignBottom:"Abaxo",alignNone:"Nenguna",invalidValue:"Valor inválidu",invalidHeight:"L'altor tien de ser un númberu.",invalidWidth:"L'anchor tien de ser un númberu.",invalidCssLength:'El valor especificáu pal campu "%1" tien de ser un númberu positivu con o sin una unidá de midida CSS válida (px, %, in, cm, mm, em, ex, pt, or pc).',
invalidHtmlLength:'El valor especificáu pal campu "%1" tien de ser un númberu positivu con o sin una unidá de midida HTML válida (px o %).',invalidInlineStyle:'El valor especificáu pal estilu en llinia tien de consistir en una o más tuples col formatu de "nome : valor", separaes con puntu y coma.',cssLengthTooltip:"Escribe un númberu pa un valor en píxeles o un númberu con una unidá CSS válida (px, %, in, cm, mm, em, ex, pt, or pc).",unavailable:'%1\x3cspan class\x3d"cke_accessibility"\x3e, nun ta disponible\x3c/span\x3e',
keyboard:{8:"Backspace",13:"Enter",16:"Shift",17:"Ctrl",18:"Alt",32:"Space",35:"End",36:"Home",46:"Delete",224:"Command"},keyboardShortcut:"Keyboard shortcut"}};