<?php
namespace Code\Framework\Paradigm\Models;
use Humble;
/**    
 *
 * Manager for workflow elements
 *
 * See Title
 *
 * PHP version 7.2+
 *
 * @category   Logical Model
 * @package    Workflow
 * @author     Rick Myers <rick@humbleprogramming.com>
 * @copyright  2007-Present, Rick Myers <rick@humbleprogramming.com>
 * @license    https://humbleprogramming.com/license.txt
 * @version    1.0
 * @link       https://humbleprogramming.com/docs/class-Paradigm_Models_Element.html
 * @since      File available since Version 1.0.1
 */
class Element extends Model
{

    /**
     * Constructor
     */
    public function __construct() {
        parent::__construct();
    }

    /**
     * Required for Helpers, Models, and Events, but not Entities
     *
     * @return system
     */
    public function getClassName() {
        return __CLASS__;
    }

    /**
     * Creates an entry in mongo and uses the mongo unique ID as the ID for the element
     *
     * The workflow editor needs a unique ID for each element, so we are going to use the Mongo uniq ID generated by saving a new element
     * and then copy that value into the ID field.
     *
     * @return array
     */
    public function create() {
        $element = Humble::collection('paradigm/elements');
        $element->setShape($this->getShape());
        $element->setType($this->getType());
        $element->setConfigured($this->getConfigured());
        $results = $element->add();         //By calling "add", I now get the mongo unique _id value
        $element->_document($results);      //Sets the document object to now include the _id value
        $element->setId($results['_id']);   //And now I make the id the same as the _id
        return $element->save();            //and we save it off
    }
}